const ServiceClient = require('../../shared/services/httpClient');

/**
 * Notification Service Client
 * Handles all communication with the Notification Service
*/
class NotificationServiceClient {
  constructor() {
    const notificationServiceUrl = process.env.NOTIFICATION_SERVICE_URL || 'http://localhost:3004';
    this.client = new ServiceClient(notificationServiceUrl, 'Notification Service');
  }

  /**
   * Send reservation confirmed notification (auto-confirm flow)
   * @param {object} reservation - Reservation object
   * @param {object} user - User object
   * @param {object} stall - Stall object
   */
  async sendReservationConfirmed(reservation, user, stall) {
    try {
      await this.client.post('/api/notifications/send', {
        type: 'RESERVATION_CONFIRMED',
        recipient: reservation.userId,
        recipientEmail: user.email,
        reservation: reservation._id,
        data: {
          userName: user.name,
          reservationNumber: reservation.reservationNumber,
          stallNumber: stall.stallNumber,
          stallLocation: stall.location ? 
            `${stall.location.zone || ''} ${stall.location.floor || ''}`.trim() : 
            'N/A',
          startDate: reservation.startDate,
          endDate: reservation.endDate,
          totalAmount: reservation.totalAmount,
          duration: reservation.duration,
          purpose: reservation.purpose,
          specialRequests: reservation.specialRequests,
          amenities: stall.amenities || [],
          // QR code will be generated by notification service
          reservationId: reservation._id.toString()
        }
      });
      console.log(`Reservation confirmed notification sent for ${reservation.reservationNumber}`);
    } catch (error) {
      console.error('Failed to send reservation confirmed notification:', error.message);
      // Don't throw - notification failure shouldn't break reservation creation
    }
  }

  /**
   * Send reservation cancelled notification
   * @param {object} reservation - Reservation object
   * @param {object} user - User object
   * @param {object} stall - Stall object
   * @param {number} refundAmount - Refund amount
   * @param {number} refundPercentage - Refund percentage
   */
  async sendReservationCancelled(reservation, user, stall, refundAmount, refundPercentage) {
    try {
      await this.client.post('/api/notifications/send', {
        type: 'RESERVATION_CANCELLED',
        recipient: reservation.userId,
        recipientEmail: user.email,
        reservation: reservation._id,
        data: {
          userName: user.name,
          reservationNumber: reservation.reservationNumber,
          stallNumber: stall.stallNumber,
          cancellationReason: reservation.cancellationReason,
          refundAmount: refundAmount || 0,
          refundPercentage: refundPercentage || 0,
          cancelledAt: reservation.cancelledAt
        }
      });
      console.log(`Reservation cancelled notification sent for ${reservation.reservationNumber}`);
    } catch (error) {
      console.error('Failed to send reservation cancelled notification:', error.message);
    }
  }

  /**
   * Send reservation reminder (before event starts)
   * @param {object} reservation - Reservation object
   * @param {object} user - User object
   * @param {object} stall - Stall object
   */
  async sendReservationReminder(reservation, user, stall) {
    try {
      await this.client.post('/api/notifications/send', {
        type: 'RESERVATION_REMINDER',
        recipient: reservation.userId,
        recipientEmail: user.email,
        reservation: reservation._id,
        data: {
          userName: user.name,
          reservationNumber: reservation.reservationNumber,
          stallNumber: stall.stallNumber,
          stallLocation: stall.location ? 
            `${stall.location.zone || ''} ${stall.location.floor || ''}`.trim() : 
            'N/A',
          startDate: reservation.startDate,
          endDate: reservation.endDate
        }
      });
      console.log(`Reservation reminder sent for ${reservation.reservationNumber}`);
    } catch (error) {
      console.error('Failed to send reservation reminder:', error.message);
    }
  }

  /**
   * Generate and send QR code
   * @param {string} reservationId - Reservation ID
   * @param {object} reservation - Reservation object
   * @param {object} user - User object
   */
  async generateQRCode(reservationId, reservation, user) {
    try {
      await this.client.post('/api/notifications/qr-code/generate', {
        reservationId,
        recipientEmail: user.email,
        data: {
          reservationNumber: reservation.reservationNumber,
          stallId: reservation.stallId,
          userId: reservation.userId,
          startDate: reservation.startDate,
          endDate: reservation.endDate,
          status: reservation.status
        }
      });
      console.log(`QR code generated and sent for ${reservation.reservationNumber}`);
    } catch (error) {
      console.error('Failed to generate QR code:', error.message);
    }
  }

  /**
   * Check notification service health
   * @returns {Promise<boolean>} Service health status
   */
  async checkHealth() {
    try {
      return await this.client.healthCheck();
    } catch (error) {
      console.error('Notification service health check failed:', error.message);
      return false;
    }
  }
}

// Export singleton instance
module.exports = new NotificationServiceClient();
